import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import Link from 'next/link'
import { getDictionary, hasLocale, type Locale } from '@/lib/i18n/dictionaries'
import { Clock, ArrowLeft } from 'lucide-react'

type Props = {
  params: Promise<{ lang: string; slug: string }>
}

interface BlogPost {
  slug: string
  category: string
  title: string
  excerpt: string
  readTime: string
  color: string
  content: string[]
}

const blogPosts: Record<string, BlogPost> = {
  'skincare-routine-dubai-summer': {
    slug: 'skincare-routine-dubai-summer',
    category: 'Dubai Climate',
    title: "The Ultimate Skincare Routine for Dubai's Summer Heat",
    excerpt: 'Discover how to protect and nourish your skin in extreme heat and humidity with our expert-curated routine designed specifically for the UAE climate.',
    readTime: '5 min',
    color: '#C9A96E',
    content: [
      "Dubai's summer is unlike anywhere else on earth. With temperatures regularly exceeding 45°C and humidity levels that can make the air feel like a warm, wet blanket, your skin faces unique challenges that standard skincare routines simply aren't designed to handle.",
      "## Why Dubai's Climate Demands a Different Approach",
      "The combination of intense UV radiation, extreme heat, and high humidity creates a perfect storm for skin issues. Your skin's natural barrier is constantly under attack — UV rays break down collagen, heat triggers excess sebum production, and humidity can paradoxically dehydrate your skin by disrupting its moisture balance.",
      "Add to this the constant transition between scorching outdoor heat and aggressively air-conditioned interiors, and you have a recipe for confused, stressed skin.",
      "## The Morning Routine",
      "Start with a pH-balanced, sulfate-free cleanser. In Dubai's heat, you may be tempted to use a stronger cleanser to combat oiliness, but this strips your skin's protective barrier. A gentle cleanser removes overnight buildup without compromising your skin's defenses.",
      "Apply a Vitamin C serum immediately after cleansing. Dubai's UV index regularly hits 11+ (extreme), making antioxidant protection non-negotiable. Vitamin C neutralizes free radicals generated by UV exposure and helps prevent the hyperpigmentation that's so common in high-sun environments.",
      "Choose a gel-based or water-gel moisturizer rather than a cream. Heavy creams will feel suffocating in the heat and can clog pores. Look for ingredients like hyaluronic acid, niacinamide, and ceramides.",
      "SPF 50+ sunscreen is non-negotiable. Apply generously (2mg per cm² of skin) and reapply every 2 hours if you're outdoors. Choose a broad-spectrum formula that protects against both UVA and UVB rays.",
      "## The Evening Routine",
      "Start with a micellar water or cleansing oil to remove sunscreen and pollution, followed by your gentle cleanser. Dubai's air quality, while improved, still carries particulate matter that can clog pores.",
      "Use a chemical exfoliant containing AHAs (glycolic or lactic acid) or BHAs (salicylic acid) 2-3 times per week. This removes the dead skin cells that accumulate faster in hot climates and helps prevent the congestion that leads to breakouts.",
      "Evening is the time for your active ingredients. Retinol, peptides, or niacinamide can work their magic overnight without UV interference.",
      "At night, you can afford to use a slightly richer formula. Your skin repairs itself during sleep, and providing adequate moisture supports this process.",
      "## Key Ingredients for Dubai Skin",
      "Niacinamide is perhaps the most valuable ingredient for Dubai residents. It regulates sebum production, strengthens the skin barrier, reduces hyperpigmentation, and has anti-inflammatory properties — addressing virtually every concern that Dubai's climate creates.",
      "Hyaluronic acid is essential, but use it correctly. Apply it to damp skin and seal it in with a moisturizer. In low-humidity environments (like air-conditioned spaces), hyaluronic acid can actually draw moisture from your skin if not properly sealed.",
      "Ceramides help rebuild and maintain the skin barrier that's constantly being compromised by environmental stressors. Look for products containing ceramide NP, AP, and EOP for comprehensive barrier support.",
    ],
  },
  'hyaluronic-acid-guide': {
    slug: 'hyaluronic-acid-guide',
    category: 'Ingredients Science',
    title: 'Hyaluronic Acid: The Complete Guide to Skin Hydration',
    excerpt: 'Everything you need to know about the most powerful hydrating ingredient in modern skincare.',
    readTime: '7 min',
    color: '#7BA7BC',
    content: [
      "Hyaluronic acid (HA) has become one of the most talked-about ingredients in skincare, and for good reason. This naturally occurring molecule has an extraordinary ability to hold up to 1,000 times its weight in water, making it one of the most effective hydrating ingredients available.",
      "## What Is Hyaluronic Acid?",
      "Despite its name, hyaluronic acid isn't actually an acid in the traditional sense — it won't exfoliate or irritate your skin. It's a glycosaminoglycan, a type of sugar molecule that occurs naturally in your body, particularly in your skin, connective tissue, and eyes.",
      "Your skin naturally produces hyaluronic acid, but production decreases with age, sun exposure, and environmental stress. By the time you're in your 40s, your skin may have lost up to 50% of its natural HA content.",
      "## The Different Molecular Weights",
      "Not all hyaluronic acid is created equal. The molecule comes in different sizes, and each size behaves differently on your skin.",
      "High molecular weight HA sits on the surface of your skin, forming a moisture-retaining film. It provides immediate plumping and hydration but doesn't penetrate deeply. This is what gives that immediate 'dewy' effect.",
      "Medium molecular weight HA penetrates slightly deeper into the upper layers of the epidermis, providing more sustained hydration.",
      "Low molecular weight HA can penetrate into the deeper layers of the skin, providing hydration where it's needed most and supporting the skin's own HA production.",
      "The best hyaluronic acid products contain multiple molecular weights to provide hydration at every level of the skin.",
      "## How to Use Hyaluronic Acid Correctly",
      "The most common mistake people make with hyaluronic acid is applying it to dry skin. HA works by attracting and binding water molecules — if there's no water available, it will draw moisture from the deeper layers of your skin, potentially causing dehydration.",
      "Always apply hyaluronic acid to damp skin, ideally immediately after cleansing while your skin is still slightly wet. Then seal it in with a moisturizer to prevent the water from evaporating.",
      "In very dry climates or heavily air-conditioned environments, consider using a facial mist before applying HA to ensure there's sufficient moisture for it to work with.",
      "## Hyaluronic Acid in Dubai's Climate",
      "Dubai presents a unique challenge for hyaluronic acid users. Outdoors, the humidity can be high enough for HA to work effectively. But indoors, air conditioning creates an extremely dry environment where HA can backfire if not properly sealed.",
      "The solution is to use a HA serum followed immediately by a moisturizer containing occlusive ingredients like squalane, shea butter, or dimethicone. This creates a barrier that locks in the moisture HA has attracted.",
      "## Combining with Other Ingredients",
      "Hyaluronic acid plays well with virtually every other skincare ingredient. It can be layered with vitamin C, retinol, niacinamide, and AHAs/BHAs without any adverse interactions.",
      "In fact, using HA alongside potentially irritating actives like retinol or AHAs can help buffer their effects and reduce irritation while maintaining hydration.",
    ],
  },
  'anti-aging-routine-uae': {
    slug: 'anti-aging-routine-uae',
    category: 'Anti-Aging',
    title: 'Anti-Aging Skincare: A Science-Backed Approach for UAE Skin',
    excerpt: 'How to build an effective anti-aging routine that works with the UAE climate, not against it.',
    readTime: '8 min',
    color: '#B76E79',
    content: [
      "Aging is inevitable, but how quickly and visibly it occurs is significantly influenced by your environment and skincare choices. In the UAE, where UV radiation is intense year-round and environmental stressors are significant, a proactive anti-aging approach isn't vanity — it's skin health.",
      "## Understanding Skin Aging in the UAE",
      "Skin aging occurs through two distinct processes: intrinsic aging (genetic, inevitable) and extrinsic aging (environmental, preventable). In the UAE, extrinsic aging factors are particularly aggressive.",
      "UV radiation is the primary driver of premature aging, responsible for up to 80% of visible skin aging. Dubai's UV index regularly reaches 'extreme' levels (11+), meaning unprotected skin can sustain significant damage in as little as 10-15 minutes.",
      "## The Foundation: Sun Protection",
      "No anti-aging routine is complete without comprehensive sun protection. SPF 50+ broad-spectrum sunscreen, applied daily and reapplied every 2 hours during sun exposure, is the single most effective anti-aging intervention available.",
      "Look for sunscreens containing zinc oxide or titanium dioxide (physical/mineral filters) for broad-spectrum protection, or modern chemical filters like Tinosorb S and M that provide excellent UVA protection.",
      "## Retinoids: The Gold Standard",
      "Retinoids (vitamin A derivatives) are the most extensively researched anti-aging ingredients in dermatology. They work by increasing cell turnover, stimulating collagen production, and normalizing skin cell function.",
      "Retinol is the most widely available over-the-counter retinoid. Start with a low concentration (0.025-0.05%) and gradually increase as your skin builds tolerance. Use it at night only, as it increases photosensitivity.",
      "Retinal (retinaldehyde) is approximately 11 times more potent than retinol and converts to retinoic acid more efficiently. It's available without prescription and tends to cause less irritation than prescription retinoids.",
      "## Vitamin C: Antioxidant Protection and Collagen Support",
      "L-ascorbic acid (vitamin C) serves double duty in an anti-aging routine. As an antioxidant, it neutralizes the free radicals generated by UV exposure that damage collagen and DNA. As a collagen co-factor, it's essential for the synthesis of new collagen.",
      "Use a stable vitamin C serum (10-20% L-ascorbic acid, pH 2.5-3.5) in the morning before sunscreen. The combination of vitamin C and SPF provides significantly better protection than either alone.",
      "## Peptides: Signaling Molecules for Skin Renewal",
      "Peptides are short chains of amino acids that act as signaling molecules in the skin. Different peptides have different functions — some stimulate collagen production, others inhibit muscle contractions that cause expression lines, and others support the skin barrier.",
      "Unlike retinoids, peptides are generally well-tolerated and can be used by those with sensitive skin. They work best as part of a comprehensive routine rather than as standalone treatments.",
      "## Building Your Routine",
      "Morning: Gentle cleanser, Vitamin C serum, Moisturizer with SPF 50+. Evening: Double cleanse, Retinoid (2-3x per week initially), Niacinamide serum, Rich moisturizer.",
      "Consistency is key. Anti-aging ingredients work gradually — expect to see meaningful results after 3-6 months of consistent use.",
    ],
  },
  'best-skincare-routine-dry-skin-dubai': {
    slug: 'best-skincare-routine-dry-skin-dubai',
    category: 'Dry Skin',
    title: 'Best Skincare Routine for Dry Skin in Dubai',
    excerpt: "Combat the drying effects of Dubai's climate with this comprehensive routine for dry skin types.",
    readTime: '6 min',
    color: '#A8C5A0',
    content: [
      "Dry skin in Dubai might seem counterintuitive — after all, isn't it humid here? The reality is more complex. While outdoor humidity can be high, the combination of intense air conditioning, UV exposure, and hard water creates conditions that are particularly challenging for dry skin types.",
      "## Understanding Dry Skin vs. Dehydrated Skin",
      "Before building your routine, it's important to distinguish between dry skin (a skin type) and dehydrated skin (a skin condition). Dry skin lacks oil (sebum), while dehydrated skin lacks water. You can have oily skin that's dehydrated, or dry skin that's also dehydrated.",
      "In Dubai, many people experience both — their skin type may be dry, and the environment further dehydrates it. This requires a two-pronged approach: adding oil to address dryness and adding water to address dehydration.",
      "## The Morning Routine for Dry Skin",
      "Use a cream or oil-based cleanser that cleans without stripping. Avoid foaming cleansers, which tend to be more drying. Apply a hydrating toner or essence to damp skin before your serum.",
      "Follow with hyaluronic acid serum on damp skin, then seal immediately with a rich moisturizer. Choose a moisturizer with both humectants (to attract water) and emollients/occlusives (to seal it in). Look for ingredients like shea butter, squalane, ceramides, and fatty acids.",
      "Finish with a moisturizing SPF 50+ formula. Many modern SPF products are formulated with hydrating ingredients that work well for dry skin.",
      "## The Evening Routine for Dry Skin",
      "Start with an oil cleanser to remove sunscreen and makeup without stripping your skin's natural oils. Follow with a gentle cream cleanser.",
      "Apply a hydrating serum containing hyaluronic acid, peptides, or ceramides. Apply a few drops of a nourishing facial oil (rosehip, marula, or squalane) before your moisturizer to boost hydration.",
      "Use your richest moisturizer at night. Consider a sleeping mask 2-3 times per week for intensive hydration.",
      "## Key Ingredients for Dry Skin",
      "Ceramides are essential for dry skin. They're the lipids that make up your skin's barrier, and dry skin often has a compromised barrier. Products containing ceramide NP, AP, and EOP help restore and maintain barrier function.",
      "Squalane is a lightweight, non-comedogenic oil that closely mimics your skin's natural sebum. It's excellent for dry skin because it provides oil without feeling heavy or greasy.",
      "## Lifestyle Tips for Dry Skin in Dubai",
      "Install a humidifier in your bedroom. Air conditioning removes moisture from the air, and sleeping in a dry environment can significantly worsen dry skin. A humidifier set to 40-60% humidity can make a noticeable difference.",
      "Drink plenty of water and eat foods rich in omega-3 fatty acids (fatty fish, walnuts, flaxseed). These support your skin's lipid barrier from the inside out.",
    ],
  },
  'best-skincare-routine-oily-skin-dubai': {
    slug: 'best-skincare-routine-oily-skin-dubai',
    category: 'Oily Skin',
    title: 'Best Skincare Routine for Oily Skin in Dubai',
    excerpt: "Keep shine at bay and maintain clear skin with this expert routine for oily skin in Dubai's heat.",
    readTime: '6 min',
    color: '#9B8EA8',
    content: [
      "Oily skin in Dubai's heat can feel like a constant battle. The combination of high temperatures, humidity, and UV exposure can send your sebaceous glands into overdrive, leading to shine, enlarged pores, and breakouts. But with the right routine, oily skin can actually be an advantage — it tends to age more slowly and is naturally more resilient.",
      "## Why Oily Skin Gets Worse in Dubai",
      "Heat directly stimulates sebum production. Your skin produces more oil as a protective response to heat and UV radiation. Add humidity to the mix, and you have conditions that can make even normal skin feel oily.",
      "The mistake many oily skin types make is over-cleansing or using harsh, stripping products to combat the oil. This actually backfires — when you strip your skin's natural oils, it responds by producing even more sebum to compensate.",
      "## The Morning Routine for Oily Skin",
      "Use a gentle, pH-balanced gel cleanser. Avoid harsh foaming cleansers with sulfates, which strip the skin and trigger rebound oiliness.",
      "Apply a niacinamide serum (5-10%) — it regulates sebum production, minimizes pore appearance, and has anti-inflammatory properties that help prevent breakouts.",
      "Yes, oily skin needs moisturizer. Skipping it leads to dehydration, which triggers more oil production. Choose a gel-based or water-gel moisturizer that hydrates without adding oil. Finish with an oil-free, mattifying SPF.",
      "## The Evening Routine for Oily Skin",
      "Use micellar water or a gentle cleansing oil to remove sunscreen and makeup, then follow with your gel cleanser.",
      "Use a BHA (salicylic acid 1-2%) exfoliant 2-3 times per week — it's oil-soluble and penetrates pores to dissolve congestion.",
      "Retinol is excellent for oily skin — it normalizes cell turnover, reduces pore size, and helps prevent breakouts. Start with a low concentration and build up gradually. Finish with a lightweight gel moisturizer.",
      "## Ingredients to Seek Out",
      "Salicylic acid (BHA) is the gold standard for oily, acne-prone skin. It exfoliates inside the pore, preventing the congestion that leads to blackheads and breakouts.",
      "Niacinamide regulates sebum production and is one of the few ingredients with clinical evidence for reducing pore size appearance.",
      "Clay (kaolin, bentonite) in masks can help absorb excess oil and deep-clean pores. Use a clay mask 1-2 times per week.",
    ],
  },
  'skin-barrier-repair-dubai-climate': {
    slug: 'skin-barrier-repair-dubai-climate',
    category: 'Skin Barrier',
    title: "How to Repair Your Skin Barrier in Dubai's Climate",
    excerpt: "AC exposure, UV rays, and heat can damage your skin barrier. Here's how to restore it.",
    readTime: '7 min',
    color: '#C9A96E',
    content: [
      "Your skin barrier — the outermost layer of your skin — is your body's first line of defense against the environment. In Dubai, this barrier faces an extraordinary array of challenges: intense UV radiation, extreme heat, aggressive air conditioning, hard water, and pollution.",
      "## What Is the Skin Barrier?",
      "The skin barrier, technically called the stratum corneum, consists of dead skin cells (corneocytes) held together by lipids (ceramides, fatty acids, and cholesterol) in a structure often described as 'bricks and mortar.' This structure prevents water loss and keeps irritants, allergens, and pathogens out.",
      "When the barrier is intact, skin looks plump, smooth, and healthy. When it's compromised, you may experience dryness, flakiness, redness, sensitivity, breakouts, and a dull complexion.",
      "## Signs of a Damaged Skin Barrier",
      "Increased sensitivity and reactivity to products that previously didn't cause issues is often the first sign. Your skin may sting or burn when you apply skincare products, even gentle ones.",
      "Persistent dryness that doesn't respond to moisturizer, rough or flaky texture, redness or inflammation, and frequent breakouts despite a consistent routine are all indicators of barrier damage.",
      "## Dubai's Specific Barrier Challenges",
      "UV radiation breaks down the lipids in your skin barrier and damages the DNA of skin cells. Air conditioning creates an extremely dry environment that accelerates transepidermal water loss (TEWL).",
      "Dubai's hard tap water contains high levels of calcium and magnesium that can disrupt your skin's pH. Over-exfoliation is a common cause of barrier damage — many people over-exfoliate in an attempt to combat the congestion and dullness that Dubai's environment can cause.",
      "## The Barrier Repair Protocol",
      "Step 1: Simplify your routine. When your barrier is damaged, less is more. Strip back to the basics: a gentle cleanser, a barrier-repairing moisturizer, and SPF. Pause all actives (retinoids, AHAs, BHAs, vitamin C) until your barrier has recovered.",
      "Step 2: Use a ceramide-rich moisturizer. Ceramides are the primary lipids in your skin barrier. Products containing ceramide NP, AP, and EOP in combination with cholesterol and fatty acids most closely mimic your skin's natural barrier composition.",
      "Step 3: Add a barrier-supporting serum. Look for serums containing panthenol (provitamin B5), which has proven barrier-repair properties, or centella asiatica (cica), which has anti-inflammatory and wound-healing effects.",
      "Step 4: Use an occlusive at night. Applying a thin layer of an occlusive product (petrolatum, squalane, or a rich balm) as the last step in your evening routine creates a physical barrier that prevents water loss while your skin repairs itself overnight.",
      "## Timeline for Recovery",
      "With a simplified, barrier-focused routine, most people see improvement within 1-2 weeks. Full barrier repair can take 4-6 weeks. During this time, resist the temptation to reintroduce actives too quickly.",
      "Once your barrier has recovered, reintroduce actives one at a time, starting with the gentlest options and giving your skin 2-4 weeks to adjust before adding anything new.",
    ],
  },
}

export async function generateStaticParams() {
  const slugs = Object.keys(blogPosts)
  const langs = ['en', 'ar', 'tr', 'ru', 'de', 'fr', 'es', 'it', 'zh']
  return langs.flatMap((lang) => slugs.map((slug) => ({ lang, slug })))
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { lang, slug } = await params
  if (!hasLocale(lang)) return {}
  const post = blogPosts[slug]
  if (!post) return {}

  return {
    title: `${post.title} | By Hayat Skin`,
    description: post.excerpt,
    keywords: [post.category.toLowerCase(), 'skincare dubai', 'luxury skincare uae', 'by hayat skin'],
    openGraph: {
      title: `${post.title} | By Hayat Skin`,
      description: post.excerpt,
    },
  }
}

export default async function BlogPostPage({ params }: Props) {
  const { lang, slug } = await params
  if (!hasLocale(lang)) notFound()

  const post = blogPosts[slug]
  if (!post) notFound()

  const locale = lang as Locale
  const dict = await getDictionary(locale)

  const related = Object.values(blogPosts)
    .filter((p) => p.slug !== slug)
    .slice(0, 3)

  return (
    <div className="min-h-screen pt-28" style={{ background: '#0F0E0C' }}>

      {/* ── Hero ── */}
      <div
        style={{
          background: `linear-gradient(135deg, ${post.color}12 0%, #141210 50%, #0F0E0C 100%)`,
          borderBottom: '1px solid rgba(201,169,110,0.1)',
        }}
      >
        <div className="container-luxury py-14">
          <Link
            href={`/${locale}/blog`}
            className="inline-flex items-center gap-2 mb-8 transition-colors duration-300"
            style={{ color: 'rgba(201,169,110,0.5)', fontSize: '0.65rem', letterSpacing: '0.2em', textTransform: 'uppercase' }}
          >
            <ArrowLeft size={12} />
            {dict.blog.label}
          </Link>

          <div className="flex items-center gap-3 mb-5">
            <span
              className="text-[0.58rem] tracking-[0.18em] uppercase px-3 py-1 rounded-full font-medium"
              style={{ background: post.color + '20', color: post.color, border: `1px solid ${post.color}30` }}
            >
              {post.category}
            </span>
            <div className="flex items-center gap-1.5" style={{ color: 'rgba(201,169,110,0.4)', fontSize: '0.62rem' }}>
              <Clock size={11} />
              <span>{post.readTime} read</span>
            </div>
          </div>

          <h1
            style={{
              fontFamily: 'var(--font-cormorant), Georgia, serif',
              fontWeight: 300,
              fontSize: 'clamp(2rem, 4vw, 3.5rem)',
              color: '#F5EFE6',
              letterSpacing: '-0.01em',
              lineHeight: 1.15,
              maxWidth: '760px',
            }}
          >
            {post.title}
          </h1>
        </div>
      </div>

      {/* ── Content ── */}
      <div className="container-luxury py-12">
        <div className="grid grid-cols-1 lg:grid-cols-[1fr_280px] gap-12">

          {/* ── Article ── */}
          <article>
            {/* Excerpt / lead */}
            <p
              className="text-base leading-relaxed mb-10 pb-10"
              style={{
                color: 'rgba(245,239,230,0.65)',
                borderBottom: '1px solid rgba(201,169,110,0.1)',
                fontSize: '1.05rem',
                lineHeight: 1.8,
              }}
            >
              {post.excerpt}
            </p>

            {/* Body */}
            <div className="space-y-6">
              {post.content.map((paragraph, i) => {
                if (paragraph.startsWith('## ')) {
                  return (
                    <h2
                      key={i}
                      style={{
                        fontFamily: 'var(--font-cormorant), Georgia, serif',
                        fontWeight: 300,
                        fontSize: 'clamp(1.4rem, 2.5vw, 1.9rem)',
                        color: '#F5EFE6',
                        marginTop: '2.5rem',
                        marginBottom: '0.5rem',
                        letterSpacing: '0.01em',
                        lineHeight: 1.2,
                      }}
                    >
                      {paragraph.replace('## ', '')}
                    </h2>
                  )
                }
                return (
                  <p
                    key={i}
                    style={{
                      color: 'rgba(245,239,230,0.6)',
                      lineHeight: 1.85,
                      fontSize: '0.95rem',
                    }}
                  >
                    {paragraph}
                  </p>
                )
              })}
            </div>

            {/* Back link */}
            <div className="mt-14 pt-8" style={{ borderTop: '1px solid rgba(201,169,110,0.1)' }}>
              <Link
                href={`/${locale}/blog`}
                className="inline-flex items-center gap-2 transition-colors duration-300"
                style={{ color: '#C9A96E', fontSize: '0.65rem', letterSpacing: '0.15em', textTransform: 'uppercase' }}
              >
                <ArrowLeft size={12} />
                {dict.blog.label}
              </Link>
            </div>
          </article>

          {/* ── Sidebar ── */}
          <aside className="space-y-6">

            {/* Related posts */}
            <div>
              <div className="flex items-center gap-3 mb-5">
                <div className="h-px flex-1" style={{ background: 'rgba(201,169,110,0.1)' }} />
                <span style={{ color: 'rgba(201,169,110,0.4)', fontSize: '0.58rem', letterSpacing: '0.3em', textTransform: 'uppercase' }}>
                  Related
                </span>
                <div className="h-px flex-1" style={{ background: 'rgba(201,169,110,0.1)' }} />
              </div>

              <div className="space-y-3">
                {related.map((relPost) => (
                  <Link
                    key={relPost.slug}
                    href={`/${locale}/blog/${relPost.slug}`}
                    className="group block p-4 transition-all duration-400"
                    style={{
                      background: '#141210',
                      border: '1px solid rgba(201,169,110,0.1)',
                    }}
                  >
                    <span
                      className="text-[0.52rem] tracking-[0.12em] uppercase px-2 py-0.5 rounded-full font-medium mb-2 inline-block"
                      style={{ background: relPost.color + '20', color: relPost.color }}
                    >
                      {relPost.category}
                    </span>
                    <h3
                      className="leading-snug mb-1.5 transition-colors duration-300"
                      style={{
                        fontFamily: 'var(--font-cormorant), Georgia, serif',
                        fontWeight: 300,
                        fontSize: '0.95rem',
                        color: 'rgba(245,239,230,0.8)',
                        lineHeight: 1.35,
                      }}
                    >
                      {relPost.title}
                    </h3>
                    <div className="flex items-center gap-1.5" style={{ color: 'rgba(201,169,110,0.35)', fontSize: '0.58rem' }}>
                      <Clock size={9} />
                      <span>{relPost.readTime} read</span>
                    </div>
                  </Link>
                ))}
              </div>
            </div>

            {/* CTA card */}
            <div
              className="p-6"
              style={{
                background: 'linear-gradient(135deg, rgba(201,169,110,0.07) 0%, rgba(160,120,64,0.04) 100%)',
                border: '1px solid rgba(201,169,110,0.15)',
              }}
            >
              <div style={{ width: '24px', height: '1px', background: 'rgba(201,169,110,0.4)', marginBottom: '1rem' }} />
              <h3
                className="mb-2"
                style={{
                  fontFamily: 'var(--font-cormorant), Georgia, serif',
                  fontWeight: 300,
                  fontSize: '1.25rem',
                  color: '#F5EFE6',
                  lineHeight: 1.2,
                }}
              >
                {dict.consultation.headline}
              </h3>
              <p
                className="mb-5 leading-relaxed"
                style={{ color: 'rgba(245,239,230,0.45)', fontSize: '0.8rem' }}
              >
                {dict.consultation.subheadline}
              </p>
              <Link
                href={`/${locale}/consultation`}
                className="block text-center py-3 transition-all duration-300"
                style={{
                  background: 'linear-gradient(135deg, #A07840 0%, #C9A96E 100%)',
                  color: '#0F0E0C',
                  fontSize: '0.62rem',
                  letterSpacing: '0.18em',
                  textTransform: 'uppercase',
                  fontWeight: 500,
                }}
              >
                {dict.consultation.cta}
              </Link>
            </div>

          </aside>
        </div>
      </div>
    </div>
  )
}